# Generated by Django 5.2.3 on 2025-07-09 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_teammember_facebook_url_teammember_linkedin_url_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicecategory',
            options={'verbose_name': 'Service Category 1', 'verbose_name_plural': 'Service Categories'},
        ),
    ]
