# Generated by Django 5.2.3 on 2025-06-16 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_organizerprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmessage',
            name='organizer',
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='email',
            field=models.EmailField(default='test@example.com', max_length=254),
        ),
    ]
