# Generated by Django 5.2.3 on 2025-06-16 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_service_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='price',
        ),
    ]
