# Generated by Django 5.2 on 2025-07-02 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_partner_teammember_alter_order_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Partner',
        ),
        migrations.DeleteModel(
            name='TeamMember',
        ),
    ]
