# Generated by Django 5.2 on 2025-07-05 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_providerreview'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProviderReview',
        ),
    ]
